### ISSUE TITLE
Incompat counter should display total number of issues reported for a domain

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [andreicristianpetcu/incompat#7] opened 2019-11-12 09:39 UTC
**Browser / Version**
Firefox Nightly 72.0a1 (2019-11-11)

**Operating System**
Windows 10

**Prerequisites:**
- Install the Incompat add-on, v. 1.1.0

**Steps to reproduce:**
1. Navigate to: https://github.com/webcompat/web-bugs/issues/44408
2. Observe the incompat add-on counter.

**Expected Behavior:**
The counter displays the number of all reported issues on https://github.com/webcompat/web-bugs/issues.

**Actual Behavior:**
The counter displays only eh number of Opened issues on https://github.com/webcompat/web-bugs/issues.

**Notes:**
1. Screenshot attached.

**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan
@cipriansv

![image](https://user-images.githubusercontent.com/16573771/68660026-14e84180-0541-11ea-9f4d-f016b5268e9f.png)

**Comment by softvision-sergiulogigan** [comment] 2019-11-12 10:00
I think this requires more context:

While triaging, we find it useful to know if there are any other logged issues on webcompat (either closed or opened).

Here's an example: https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=lavasoft

If we received another "lavasoft" issue, the Incompat counter would display 1. If we would rely 100% on the Incompat add-on to trigger us to do a search for duplicates, in this case, we would not do that, and just go ahead and try to reproduce it. However, if we already knew there are some other Closed issues, we would try to find a duplicate of the current one.

**Comment by softvision-oana-arbuzov** [comment] 2019-11-12 10:42
Maybe something like this: 

![image](https://user-images.githubusercontent.com/12184325/68664915-ce4b1500-0549-11ea-949d-b875efb1b680.png)

**Comment by andreicristianpetcu** [comment] 2019-11-12 20:39
I modified the tooltip to show both the opened and closed items.
The WebExtension API prevents me from showing more info that in that square with the number. You either get closed, opened or total.

I can try to build a popup that shows more info but that would be a bit more complicated.
Does this help you or do you want to iterate some more on this feature?  @softvision-oana-arbuzov 

![image](https://user-images.githubusercontent.com/922368/68708489-81445e80-059c-11ea-87cc-8909a8448f1b.png)

![image](https://user-images.githubusercontent.com/922368/68708523-93be9800-059c-11ea-9a37-7834f5465575.png)

![image](https://user-images.githubusercontent.com/922368/68708656-da13f700-059c-11ea-9991-cbc2b88fbf40.png)
![image](https://user-images.githubusercontent.com/922368/68708758-0af42c00-059d-11ea-9579-4d9594ce014a.png)

**Comment by hensm** [comment] 2019-11-13 07:16
You could draw the counter image on the fly, though it would definitely end up cramped.
Alternatively, switch to a browser action and use badge text:

![Screenshot 2019-11-13 at 07 08 36](https://user-images.githubusercontent.com/6956633/68741154-cc825f80-05e4-11ea-9408-28860b5e4c37.png)

**Comment by softvision-sergiulogigan** [comment] 2019-11-13 08:32
Thanks @andreicristianpetcu for the modifications, and @hensm for the suggestions! This is awesome!

For me, both look great, although @hensm suggestion (the badge text) is more visual, and dos not need interaction with the add-on (like mouse hover).

I think it all boils down to the amount of time @andreicristianpetcu wants to put into this add-on and which idea appeals to him more.

**Comment by andreicristianpetcu** [comment] 2019-11-13 10:41
I'll look into the badge option. Thank you! @hensm @softvision-sergiulogigan

**Comment by andreicristianpetcu** [comment] 2019-11-13 15:49
I have 4 characters at my disposal for the browser action badge. I can use it to show the closed items while keep the location bar with the opened items. Does it sound good? @hensm @softvision-sergiulogigan @softvision-oana-arbuzov 

![image](https://user-images.githubusercontent.com/922368/68779749-d8e6d680-063d-11ea-9977-ee9a7209a920.png)

**Comment by softvision-sergiulogigan** [comment] 2019-11-13 16:00
If I understand correctly, with this solution, there will be 2 items in the bar for the Incompat add-on (the one in the address bar and the one outside it).

> The WebExtension API prevents me from showing more info that in that square with the number. You either get closed, opened or total.

I would go with the total number in the blue square in the address bar, and keep already implemented hover tooltip to show both the opened and closed items.

**Comment by andreicristianpetcu** [comment] 2019-11-13 17:25
It's a bit more complicated than that. @softvision-sergiulogigan The blue number is between 1 and 9. Above 9 I have an infinity symbol. Each number is an icon. I would need to generate PNG icons for all the possible numbers. Most web sites have more than 9 opened+closed items.

I think the simplest solution is to add the browser action with the badge number that has either the total items or closed items. I honestly don't care which one :)

**Comment by andreicristianpetcu** [comment] 2019-11-13 17:35
If I drop the pageAction and only use the browserAction I can show both items in the same place. The implementation is quite easy.

https://github.com/webcompat/web-bugs/issues/44408
![image](https://user-images.githubusercontent.com/922368/68788684-8cef5e00-064c-11ea-9686-a244b3335e6f.png)

![image](https://user-images.githubusercontent.com/922368/68788753-af817700-064c-11ea-9184-fa54a1b4d1cc.png)

**Comment by hensm** [comment] 2019-11-13 17:36
You can also set the page action icon to some arbitrary pixel data, so rather than using hardcoded images, you could draw the total issue count to a canvas and then set it to the page action.

**Comment by andreicristianpetcu** [comment] 2019-11-13 17:40
Yeah, I know but it's complicated @hensm The point was to show 2 sets of data in the same place. I'm doing this now so no need for pageAction. I'll just ship it like in https://github.com/andreicristianpetcu/incompat/issues/7#issuecomment-553517142 and I'll change it after or revert it if it's not ok :smile:

**Comment by andreicristianpetcu** [comment] 2019-11-13 17:47
I published v1.2.0 in AMO. Chrome is stuck at the really old version. I cannot update it until it passes review. Maybe everybody is busy at Chrome Dev Summit.

**Comment by andreicristianpetcu** [comment] 2019-11-13 17:59
fuck! it's messed up in AMO. Works fine on my machine. Don't update :D

**Comment by andreicristianpetcu** [comment] 2019-11-13 18:25
It might be a Nightly but and not an extension bug. This is how it looks on my computer running Nightly 
![image](https://user-images.githubusercontent.com/922368/68792075-5537e480-0653-11ea-8756-b71197dd0fba.png)
Same page on stable
![image](https://user-images.githubusercontent.com/922368/68792184-86181980-0653-11ea-93e1-695b25d5f835.png)

**Comment by hensm** [comment] 2019-11-13 18:56
@andreicristianpetcu  
`Nightly`, `Stable`, `Nightly AMO`

![Screenshot 2019-11-13 at 18 53 27](https://user-images.githubusercontent.com/6956633/68794463-f66c6e00-0646-11ea-955a-ca7591d03f4e.png)

**Comment by andreicristianpetcu** [comment] 2019-11-13 19:45
Ran mozregression
``` 3:48.99 INFO: Narrowed nightly regression window from [2019-11-11, 2019-11-13] (2 days) to [2019-11-12, 2019-11-13] (1 days) (~0 steps left)
 3:48.99 INFO: Got as far as we can go bisecting nightlies...
 3:48.99 INFO: Last good revision: 9e3f44e87a1a2be927c7fab135653c6b86b982c9 (2019-11-12)
 3:48.99 INFO: First bad revision: 2f19e7b646e0a52fa855b75c868f0a3f3a990ad3 (2019-11-13)
 3:48.99 INFO: Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=9e3f44e87a1a2be927c7fab135653c6b86b982c9&tochange=2f19e7b646e0a52fa855b75c868f0a3f3a990ad3

 3:48.99 INFO: Switching bisection method to taskcluster
 3:48.99 INFO: Getting mozilla-central builds between 9e3f44e87a1a2be927c7fab135653c6b86b982c9 and 2f19e7b646e0a52fa855b75c868f0a3f3a990ad3
 3:52.32 WARNING: Skipping build 9e3f44e87a1a: Unable to find build info using the taskcluster route 'gecko.v2.mozilla-central.shippable.revision.9e3f44e87a1a2be927c7fab135653c6b86b982c9.firefox.linux64-opt'
 3:52.33 WARNING: Skipping build 2f19e7b646e0: Unable to find build info using the taskcluster route 'gecko.v2.mozilla-central.shippable.revision.2f19e7b646e0a52fa855b75c868f0a3f3a990ad3.firefox.linux64-opt'
 3:54.43 WARNING: Skipping build 48a708577712: Unable to find build info using the taskcluster route 'gecko.v2.mozilla-central.shippable.revision.48a708577712a2eb1b19aafcda25b2aa0e607629.firefox.linux64-opt'
 3:54.44 INFO: There are no build artifacts on inbound for these changesets (they are probably too old).```

**Comment by andreicristianpetcu** [comment] 2019-11-13 19:48
not an extension issue. closing this. will report un bugzilla.

**Closed by andreicristianpetcu** 2019-11-13 19:48 UTC

**Comment by andreicristianpetcu** [comment] 2019-11-13 19:51
related to https://github.com/andreicristianpetcu/incompat/issues/7#issuecomment-553272016

I have a budget of 4 characters. The minus sign takes it down to 3 chars. Not better than the current implementation.

**Comment by hensm** [comment] 2019-11-13 19:56
https://bugzilla.mozilla.org/show_bug.cgi?id=1596176

**Comment by andreicristianpetcu** [comment] 2019-11-13 20:11
I also reported it. Now I saw your comment :) https://bugzilla.mozilla.org/show_bug.cgi?id=1596214

**Comment by andreicristianpetcu** [comment] 2019-11-13 20:38
I made a fix. The badge is transparent now :smile: 
Published to AMO.
![image](https://user-images.githubusercontent.com/922368/68802300-57576e80-0666-11ea-873f-b7843a5feeb0.png)

**Comment by hensm** [comment] 2019-11-13 21:28
Ah, I see what you're going for now. Both numbers on a single button. Not _quite_ as readable on light mode since the transparency is so low.

Apart from the Nightly bug, I'm guessing transparency is also so the open issue count isn't obscured?

Hacked together a quick example of a custom drawn icon, though the smaller text size is possibly not ideal:

![Screenshot 2019-11-13 at 21 15 15](https://user-images.githubusercontent.com/6956633/68805022-e9597a00-065a-11ea-981a-8225c725e217.png)

If you're interested:
https://jsfiddle.net/64h5m1nq/1/

**Comment by softvision-sergiulogigan** [comment] 2019-11-14 08:31
This looks good! we definitely see this as a big improvement!

This is on light mode, btw...
![image](https://user-images.githubusercontent.com/16573771/68839479-74715900-06c9-11ea-9ebc-f4fc800c471d.png)

**Comment by andreicristianpetcu** [comment] 2019-11-14 08:46
@softvision-sergiulogigan I will iterate on the colors. I will ignore how it looks on NIghtly since it's a bug. I will look at various themes.

@hensm's trick to generate numbers as images is quite clever. Will look into it.

**Comment by softvision-sergiulogigan** [comment] 2019-11-15 08:09
https://bugzilla.mozilla.org/show_bug.cgi?id=1596176 has been fixed!

Looks perfect now:
![image](https://user-images.githubusercontent.com/16573771/68927198-ea3ff800-078f-11ea-9d5b-43a3da834d12.png)

**Comment by andreicristianpetcu** [comment] 2019-11-15 09:28
```javascript
function pathRoundedRect(ctx, x, y, width, height, radius) {
	const x2 = x + width;
  const y2 = y + width;

	ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.lineTo(x2 - radius, y);  ctx.arcTo(x2, y, x2, y + radius, radius);
  ctx.lineTo(x2, y2 - radius); ctx.arcTo(x2, y2, x2 - radius, y2, radius);
  ctx.lineTo(x + radius, y2);  ctx.arcTo(x, y2, x, y2 - radius, radius);
	ctx.lineTo(x, y + radius);   ctx.arcTo(x, y, x + radius, y, radius);
  ctx.closePath();
}

function drawCounter(
    count,
    backgroundColor = "rgb(42, 138, 192)",
    textColor = "white",
    size = 16) {

  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");
  
  const radius = size * 0.15;
  const fontSize = size * 0.6;

  canvas.width = size;
  canvas.height = size;

  // Box
  ctx.fillStyle = backgroundColor;
  pathRoundedRect(ctx, 0, 0, size, size, radius);
  ctx.fill();

  // Label
  ctx.fillStyle = textColor;
  ctx.textAlign = "right";
  ctx.textBaseline = "bottom";
  ctx.font = `${fontSize}px sans-serif`;
  
  const paddingWidth = ((size / 100) * 10) / 2;
  
  ctx.fillText(
  	  count.toString(),
  	  size - (paddingWidth * 2), size + paddingWidth,
      size - (paddingWidth * 5));

  return canvas;
}


for (let i = 1; i < 201; i++ ) {
	document.body.append(
        drawCounter(i.toString(),
        "rgb(42, 138, 192)", "white", 16));
}

```

**Comment by andreicristianpetcu** [comment] 2019-11-15 09:31
I'll leave it like this for now. I think generating custom icons would be really cool. I added the code snippet here so I will not loose it :smile: https://github.com/andreicristianpetcu/incompat/issues/7#issuecomment-553611552

I'm not sure how much value this would bring. I saw very few pages with more than 9 opened issues.
