### ISSUE TITLE
The query for opened issues contains unrelated domains

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [andreicristianpetcu/incompat#6] opened 2019-11-12 09:33 UTC
**Browser / Version**
Firefox Nightly 72.0a1 (2019-11-11)

**Operating System**
Windows 10

**Prerequisites:**
- Install the Incompat add-on, v. 1.1.0

**Steps to reproduce:**
1. Navigate to: https://github.com/webcompat/web-bugs/issues/44467
2. Click on the Incompat add-on counter.

**Expected Behavior:**
Only results related to epago.correoargentino.com.ar are returned.

**Actual Behavior:**
Unrelated results are returned.

**Notes:**
1. Screenshot attached.

**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan
@cipriansv

![image](https://user-images.githubusercontent.com/16573771/68659524-0fd6c280-0540-11ea-84ec-575a15cb9c0e.png)

**Comment by softvision-sergiulogigan** [comment] 2019-11-12 12:35
Some more context:
___
For https://github.com/webcompat/web-bugs/issues/44467
The domain is epago.correoargentino.com.ar

The query for the Incompat add-on is:
is:issue is:open in:title github.com OR in:title www.github.com OR in:title m.github.com OR in:title mobile.github.com OR in:title apps.github.com OR in:title free.github.com 

This yelds 1 Open and 208 Closed issues.

If we only search for epago.correoargentino.com.ar we get only one issue.
https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=epago.correoargentino.com.ar
___
A second example:

For https://github.com/webcompat/web-bugs/issues/43953
The domain is forum.solidworks.com

The query for the Incompat add-on is:
https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+solidworks.com+OR+in%3Atitle+www.solidworks.com+OR+in%3Atitle+m.solidworks.com+OR+in%3Atitle+mobile.solidworks.com+OR+in%3Atitle+apps.solidworks.com+OR+in%3Atitle+free.solidworks.com

This yelds 0 issues.

If we only search for forum.solidworks.com we get only one issue.
https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=forum.solidworks.com

**Comment by andreicristianpetcu** [comment] 2019-11-12 12:42
This is the query I get for webcompat/web-bugs#44467 
It has 4 issues https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ar+OR+in%3Atitle+www.ar+OR+in%3Atitle+m.ar+OR+in%3Atitle+mobile.ar+OR+in%3Atitle+apps.ar+OR+in%3Atitle+free.ar

The reason why you see 1 item for github is this https://github.com/andreicristianpetcu/incompat/issues/5

It tries to fetch the items for the epago.correoargentino.com.ar domain, GH bans the request due to rate limiting and it fails back to GH issues instead of epago.correoargentino.com.ar issues.

The second example I need to look into.

**Comment by softvision-sergiulogigan** [comment] 2019-11-12 13:08
Whoa! Looks like I messed up the first example. I have edited it.
_sorry about that_

We could move some of the discussions over to Skype, if it's more easy for you. I pinged you already...

**Comment by andreicristianpetcu** [comment] 2019-11-12 20:08
I fixed the first example with forum.solidworks.com which was a total n00b messup of mine :smile:
Will be fixed in v1.1.3 
The second example is actually a duplicate of #7

**Closed by andreicristianpetcu** 2019-11-12 20:08 UTC
